### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by dragoonis**

### CODE REVIEW

**Comment by dragoonis** [comment]
Okay then. Feel free to close.

**Comment by stof** [comment]
I cannot close it. I'm not a collaborator on this repo

**Comment by fabpot** [comment]
Indeed, NUL is the abbreviation for the null character (https://en.wikipedia.org/wiki/Null_character). And that helps make the difference with `null`, the PHP value.

**Comment by dragoonis** [comment]
Makes sense.

**Pull request closed without merging**
