### PR TITLE
Prepare for php 7.2

### PR DESCRIPTION
**Pull request by hboomsma**
For php >= 7.2 (nightly)
* allow `|length` of `null`
* allow `|length` of objects not implementing `\Countable`

see https://wiki.php.net/rfc/counting_non_countables for more information.

Ran all unit tests with php 7.2 nightly

### CODE REVIEW

**Comment by Tobion** [comment]
> allow |length of objects not implementing \Countable

Why should twig still support that and hide the php warning? Counting non-countable things in twig does not make more sense than in php.

**Comment by hboomsma** [comment]
The change in behaviour in Twig when running on php >=7.2 will break projects (found out with composer/satis). So it would be nice to at least maintain BC until 3.0.

That said, there might still be good reasons why to stick with this behaviour. Having `|length` on a `null` value return `0` and for a single object `1` is not very strange but helpful in some cases. In php this was abandoned because it can hide bugs. In a template one could argue this would happen less often and the convenience to not write checks to see if something is countable, could be worth keeping the current behaviour for the future.

**Comment by stof** [comment]
I would deprecate this behavior though

**Comment by hboomsma** [comment]
@stof, depricate and remove in 3.0 seems a good path to me. Do you want me to implement it? What about version 1.x?

**Comment by stof** [comment]
no deprecations in 1.x (we cannot add new ones)

**Comment by hboomsma** [comment]
@stof are the messages sufficient? Should I create a pull with the BC part for version 1?

**Comment by fabpot** [comment]
@hboomsma Can you create a PR on the 1.x branch without the deprecations? Thanks.

**Comment by hboomsma** [comment]
@fabpot, Sure I will look into it start of next week.

**Comment by hboomsma** [comment]
@fabpot #2462

**Comment by fabpot** [comment]
I've merged the other PR on 1.x and then merged 1.x into 2.x, without the deprecation notices. Not sure they make sense.

**Pull request closed without merging**
