### PR TITLE
Revert "minor #2809 Fixed 2.x tests (yceruto)"

### PR DESCRIPTION
**Pull request by xabbuh**
This reverts commit 59c26ae211d849fdcacafa6e0f7f7b31d0f7f513, reversing
changes made to 3fd85beda4f39f800f4eb85a0a27a26298624157.

### CODE REVIEW

**Comment by xabbuh** [comment]
see https://github.com/twigphp/Twig/pull/2813#pullrequestreview-192151553

**Review by yceruto — APPROVED** [review]

**Comment by stof** [comment]
Should these tests be backported to 1.x ?
AFAICT, this test failures were actually detecting the regression (they failed because the public properties were not accessed properly). And so having them in 1.x would have prevented the bug already.

**Comment by xabbuh** [comment]
as far as I can see they are now "just" duplicates of the test added in #2813

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
