### PR TITLE
Allow Traversable objects to be used in the with tag

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Currently `with` does an `in_array()` check, this allows `Traversable`~/`JsonSerializable`~ objects to be used as they can also contain a hash.

### CODE REVIEW

**Comment by stof** [comment]
I don't think supporting JsonSerializable here makes sense. We don't support it in other places dealing with arrays or iterators in Twig (the `merge` tag for instance).

**Comment by fabpot** [comment]
I agree with @stof

**Review by fabpot — APPROVED** [review]
Should be rebased on 1.x (and a note in the CHANGELOG could be added as well)

**Comment by fabpot** [comment]
Thank you @thewilkybarkid.

**Pull request merged**
