### PR TITLE
Fix possible array to string conversion concealing actual error

### PR DESCRIPTION
**Pull request by finwe**
Not sure this solution is the best as with larger objects/arrays it makes the message very long, but it works.

### CODE REVIEW

**Comment by stof** [comment]
I would rather handle a specific display for arrays (not dumping it entirely) than printing the whole array in the exception message (which will be totally unreadable)

**Comment by stof** [comment]
btw, this need to be covered by a test to prevent regressions

**Comment by finwe** [comment]
Will elaborate.

**Comment by finwe** [comment]
Updated and added tests for all 3 defined type cases.

**Review by stof — APPROVED** [review]

**Comment by fabpot** [comment]
@finwe Looks good to me. Can you also submit a PR for the 1.x branch where the code is slightly different?

**Comment by finwe** [comment]
Sure, hopefully within a week.

**Comment by fabpot** [comment]
Closing in favor of #2624

**Pull request closed without merging**
