### PR TITLE
Deprecate PSR-0 class names

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by stof** [comment]
this won't work if the old name is used *after* the namespaced name, as the class_alias will already have been defined.

**Comment by fabpot** [comment]
@stof I know

**Comment by stof** [comment]
however, you should add the `@deprecated` on this "fake" child classes, so that IDEs know it is deprecated.

**Comment by fabpot** [comment]
Just noticed that version is wrong in the deprecated message, upcoming PR.

**Comment by fabpot** [comment]
@stof see #2865

**Pull request merged**
