### PR TITLE
Add {% with %} tag

### PR DESCRIPTION
**Pull request by xphere**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #719 |
| License | MIT |
| Doc PR | - |

Jinja flavoured `{% with %}` tag implementation.
PR related to issue https://github.com/fabpot/Twig/issues/719

### CODE REVIEW

**Comment by stof** [comment]
@hason the first syntax is totally useless though

**Comment by fabpot** [comment]
The first syntax is useful as it marks the beginning of a new scope and variables defined inside won't survive the end of the with tag:

```twig
{% with %}
  {% set foo = 'bar' %}
{% endwith %}
{# foo is not defined here #}
```

**Comment by stof** [comment]
hmm indeed. I missed that. And 👍 for that. I have use cases for that (I have a few dummy blocks in my work projects defined only to isolate some scope in the base layout).

**Comment by fabpot** [comment]
Closing in favor of #2246, where we only support the same logic as the `include` tag as proposed by @hason

**Pull request closed without merging**
