### PR TITLE
remove the C extension

### LINKED ISSUE #3474: Delete C extension code from Twig 1.*
The documentation says that "The C extension is only compatible and useful for **PHP5**." Twig 1.43.0 and above supports only PHP >= 7.1.3. Wouldn't it be a good idea to remove unmaintained code from the repository?

### PR DESCRIPTION
**Pull request by xabbuh**
fixes #3474

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Not sure, looks like a bc break, isn't it ?

**Comment by xabbuh** [comment]
I don't think so as the Twig extension is afaik not compatible with PHP 7.

**Comment by fabpot** [comment]
I kept it for historical reasons, but it's about time to remove it I suppose.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
