### PR TITLE
Add void return type

### PR DESCRIPTION
**Pull request by simonsolutions**
add void-return type to functions in order to prevent depreciation message in Symfony 6.3

### CODE REVIEW

**Comment by stof** [comment]
The `@return void` already avoids the deprecation message.

**Comment by simonsolutions** [comment]
I tried it with Symfony 6.3, but it didn't

**Comment by stof** [comment]
My guess is that you are using the stable release of the bundle. those `@return void` are only in the dev version for now.

**Comment by xabbuh** [comment]
I think the reason is that #3840 wasn't part of a release yet.

**Comment by stof** [comment]
3.6.1 is now released.

**Pull request closed without merging**
