### PR TITLE
notice: Return type of Twig\Node\Node::count() should either be compa…

### PR DESCRIPTION
**Pull request by Alexander1000**
Hello! On php 8.1 notice

@fabpot

### CODE REVIEW

**Comment by stof** [comment]
See this note in the Twig 1.x readme: https://github.com/twigphp/Twig/tree/1.x#readme

> **Twig version 1 is not maintained anymore.** Please, upgrade at your earliest convenience.

Such fixes are already applied in Twig 2.x and 3.x

**Comment by Alexander1000** [comment]
Maybe as an exception, another patch release? There are difficulties with the transition of a huge project to a new version, but I'm working on it, I hope I don't have to patch the old version anymore.

**Comment by fabpot** [comment]
Twig 1.x has been maintained for many many years, we need to end it at some point.

**Comment by stof** [comment]
Twig 2.0 was released on January 5, 2017. So you already got 5 years for that transition

**Pull request closed without merging**
