### PR TITLE
[html-extra] rename `html_classes()` to `html_attr()`

### PR DESCRIPTION
**Pull request by kbond**
This function can be used for any html attribute (ie `data-action`, `data-controller`).

### CODE REVIEW

**Comment by kbond** [comment]
If acceptable, I'll update the docs.

**Comment by stof** [comment]
it can be used for attributes containing a space-separated list. That's not for any attribute out there. So `html_attr` is too generic for what it does (thus, using the same name than the `html_attr` escaping strategy can cause confusion)

**Comment by kbond** [comment]
That's fair, maybe `html_join` or `html_attr_join`? But we'd have to configure the separator which I think would be hard (maybe not worth it).

**Comment by fabpot** [comment]
If we were to rename to function, `html_attr_join` sounds good to me.

**Comment by fabpot** [comment]
@kbond If you're ok with the new name, can you update this PR?

**Review by fabpot — CHANGES_REQUESTED** [review]
Can you add a note in the main CHANGELOG file and in doc/deprecated.rst?

**Comment by kbond** [comment]
I'm going to close this for now. I'm now feeling it's not worth the change.

**Pull request closed without merging**
