### PR TITLE
add hasser support to getAttribute()

### LINKED ISSUE #1750: Template getAttribute() does not support hasser
Using Twig with Symfony, I expected a support for hasser (just like in Symfony PropertyAccess component). Instead, Twig only supports getter and isser.

### PR DESCRIPTION
**Pull request by xabbuh**
This resolves #1750.

### CODE REVIEW

**Comment by fabpot** [comment]
Can you also update the docs?

**Comment by Tobion** [comment]
Could be considered a BC break which happens when you have a magic getter and a hasser on your object. It will now choose the other one.

**Comment by xabbuh** [comment]
Add a line to the docs. @Tobion is right about the fact that this can be considered a BC break (it was never stated before that hasser methods do work too so this hardly is a bugfix).

**Comment by fabpot** [comment]
What about adding this to Twig 2.0 only?

**Comment by xabbuh** [comment]
We could also swap the order of the checks for the hasser method and the magic `__call()` method, but merging into 2.0 would be okay for me too.

**Comment by Tobion** [comment]
+1 in 2.0. Does this have an performance impact? If I remember right, hasser support was proposed before already (although I could not find it anymore).

**Comment by xabbuh** [comment]
I don't see any performance impact (the available class methods are cached anyway and `isset()` is in O(1)).

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request closed without merging**
