### PR TITLE
Use .html.twig file extension in documentation instead of .html

### PR DESCRIPTION
**Pull request by Pepperoni1337**
Use .html.twig file extensions instead of .html

### CODE REVIEW

**Comment by fabpot** [comment]
That works for me. Can you do it everywhere in the docs in this PR?

**Comment by Pepperoni1337** [comment]
This pull request is complete and ready for review.

**Comment by fabpot** [comment]
Thank you @Pepperoni1337.

**Comment by Pepperoni1337** [comment]
I see there is some problem with CI/CD pipeline, that I am not sure how to fix. Can you please give me some instructions

**Comment by fabpot** [comment]
> I see there is some problem with CI/CD pipeline, that I am not sure how to fix. Can you please give me some instructions

I've fixed it here: https://github.com/twigphp/Twig/commit/d78cb00f8994439fb38cc231aa3efd90abb893f5

**Pull request merged**
