### PR TITLE
Fix race condition in `Environment::loadTemplate` (1.x)

### LINKED ISSUE #1836: Race condition in `Environment::loadTemplate`
The `Environment::loadTemplate` currently is subject of a race condition. It can be reproduced with the following steps:

* Set a breakpoint in `Environment::loadTemplate` at the top of the `!class_exists($cls, false)` branch.
* Step through until the `$this->cache->load($key);` call.
* Remove the on-disk cache (`rm -r app/cache/twig')
* Continue the debugger

This will result in the following fatal error:

    Compile Error: Twig_Cache_Filesystem::load(): Failed opening required '[...]/app/cache/dev/twig/4/5/451[...].php' (include_path='[...]')

The problem is that between `$this->cache->has($key)` and `$this->cache->load($key)` anything can happen.

Proposed solution: Remove `has()` and instead try to `load()` the class directly from the cache. If the class still does not exist after that, compile the template and write it to the cache and then `eval()` the generated source directly.

### PR DESCRIPTION
**Pull request by znerol**
Fixes #1836 (1.x branch)

### CODE REVIEW

**Comment by LionsAd** [comment]
This looks pretty great to me.

Probably has() would need to be retained as deprecated function though - due to BC.

**Comment by fabpot** [comment]
`has()` has just been added, so no need to keep BC here. I will review this PR tomorrow or later this week, during DrupalCon :) See you there.

**Comment by stof** [comment]
@fabpot BC is needed. The Twig_CacheInterface has already been released.

**Comment by fabpot** [comment]
No need to keep BC when the interface has been released a week ago. Let's not add overhead for no good reasons.

**Comment by fabpot** [comment]
Thanks @znerol for working on this issue.

**Comment by drzraf** [comment]
After looking at
https://github.com/twigphp/Twig/pull/2043
I wonder:
* isn't this commit reintroducing the race-condition that the file_exists() was expected to fix?
* why is @ needed? If PHP die on buggy generated code? it would be best to let the error flow out as much as PHP permits

**Pull request merged**
