### PR TITLE
Update attribute.rst

### PR DESCRIPTION
**Pull request by abdounikarim**
Hello,

I just added examples to help for this function usage.

Cheers 😉

### CODE REVIEW

**Comment by stof** [comment]
I would rather make the note about the resolution algorithm being the same than the `.` operator more visible instead of re-documenting the algorithm partially in a second place (your examples are not covering the whole algorithm)

**Comment by abdounikarim** [comment]
Thanks for your answer @stof. I don't understand your comment, but I let you update the note.  😉

**Comment by stof** [comment]
The full algorithm to resolve attribute is documented at https://twig.symfony.com/doc/3.x/templates.html#variables

Your PR documents a *partial* version of that algorithm in the doc of the `attribute()` function. A better solution is to link to the existing documentation instead, so that we don't duplicate it (and even if we decide to duplicate it, we would have to document the full algorithm as a partial doc would actually be documenting a different algorithm which would be worse)

**Comment by fabpot** [comment]
I'm going to close here as the current doc already explains all of this.
Thank you.

**Pull request closed without merging**
