### PR TITLE
Change array_key_exists to property_exists for object check

### PR DESCRIPTION
**Pull request by ghost**
PHP7.4 throws an error using array_key_exists 
changed code to use correct function: property_exists

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
There is nothing to do here: `array_key_exists` is always called with an array, see the `(array)` cast.

**Comment by fabpot** [comment]
Let's close then.

**Comment by floverdevel** [comment]
I have upgraded to PHP 7.4 today and now i have this error :
```
PHPUnit\Framework\Error\Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead
/path/to/project/vendor/twig/twig/src/Extension/CoreExtension.php:1396
```

**Comment by nicolas-grekas** [comment]
Please upgrade your version of twig.

**Comment by floverdevel** [comment]
Ok.
I thought I updated it, I will double-check tonight (or Monday morning) 😊

**Pull request closed without merging**
