### PR TITLE
handle Throwable

### PR DESCRIPTION
**Pull request by fprochazka**
Related #2041

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @fprochazka.

**Comment by CriseX** [comment]
Doesn't this pull request imply that all previous versions of PHP other than PHP7 are now unsupported.

I don't know exactly how the php parser works in this regard, however, intuitively above is true. As long as the Throwable class is not attempted to be loaded unless an exception that inherits said class is thrown the code in this pull request remains backwards compatible, however, if that is not the case then this could break compatibility with all other versions of PHP.

**Comment by xabbuh** [comment]
@CriseX The added lines don't affect execution on older PHP versions.

**Pull request merged**
