### PR TITLE
Fix BC break on escaper extension

### LINKED ISSUE #4082: call setEscaperRuntime() before calling Twig\Extension\EscaperExtension::addSafeClass().
I just started getting this error, using Symfony ^7.0 for all the bundles.

```
 bin/console c:c -v

In EscaperExtension.php line 177:
                                                                                                     
  [LogicException]                                                                                   
  You must call setEscaperRuntime() before calling Twig\Extension\EscaperExtension::addSafeClass().  
                                                                                                     
```

```
Exception trace:
  at /home/tac/g/sites/packages/vendor/twig/twig/src/Extension/EscaperExtension.php:177
 Twig\Extension\EscaperExtension->addSafeClass() at /home/tac/g/sites/packages/vendor/symfony/ux-twig-component/src/Twig/TwigEnvironmentConfigurator.php:35
 Symfony\UX\TwigComponent\Twig\TwigEnvironmentConfigurator->configure() at /home/tac/g/sites/packages/var/cache/test/ContainerBaHlBOQ/App_KernelTestDebugContainer.php:5596
 ContainerBaHlBOQ\App_KernelTestDebugContainer::getTwigService() at /home/tac/g/sites/packages/var/cache/test/ContainerBaHlBOQ/App_KernelTestDebugContainer.php:3737
 ContainerBaHlBOQ\App_KernelTestDebugContainer::getDataCollector_TwigService() at /home/tac/g/sites/packages/var/cache/test/ContainerBaHlBOQ/App_KernelTestDebugContainer.php:762
 ContainerBaHlBOQ\App_KernelTestDebugContainer::get_Container_Private_ProfilerService() at /home/tac/g/sites/packages/var/cache/test/ContainerBaHlBOQ/getConsoleProfilerListenerService.php:23
 ContainerBaHlBOQ\getConsoleProfilerListenerService::do() at /home/tac/g/sites/packages/var/cache/test/ContainerBaHlBOQ/App_KernelTestDebugContainer.php:728
 ContainerBaHlBOQ\App_KernelTestDebugContainer->load() at /home/tac/g/sites/packages/var/cache/test/ContainerBaHlBOQ/App_KernelTestDebugContainer.php:999
 ContainerBaHlBOQ\App_KernelTestDebugContainer::ContainerBaHlBOQ\{closure}() at /home/tac/g/sites/packages/vendor/symfony/event-dispatcher/EventDispatcher.php:221
 Symfony\Component\EventDispatcher\EventDispatcher->sortListeners() at /home/tac/g/sites/packages/vendor/symfony/event-dispatcher/EventDispatcher.php:70
 Symfony\Component\EventDispatcher\EventDispatcher->getListeners() at /home/tac/g/sites/packages/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:257
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->preProcess() at /home/tac/g/sites/packages/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:121
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /home/tac/g/sites/packages/vendor/symfony/console/Application.php:1046
 Symfony\Component\Console\Application->doRunCommand() at /home/tac/g/sites/packages/vendor/symfony/framework-bundle/Console/Application.php:125
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/tac/g/sites/packages/vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at /home/tac/g/sites/packages/vendor/symfony/framework-bundle/Console/Application.php:79
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/tac/g/sites/packages/vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at /home/tac/g/sites/packages/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /home/tac/g/sites/packages/vendor/autoload_runtime.php:29
 require_once() at /home/tac/g/sites/packages/bin/console:11

### PR DESCRIPTION
**Pull request by fabpot**
Closes #4082

@tacman Can you test that this fixes your issue?

### CODE REVIEW

**Comment by tacman** [comment]
I hate to ask such a simple question, but how do I install this branch as 3.8 (since other bundles require twig/twig:^3.8?

```
composer req twig/twig:dev-escaper-fix
./composer.json has been updated
Running composer update twig/twig
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires twig/twig dev-escaper-fix, found twig/twig[dev-ci-fix, 1.3.0, ..., 1.x-dev, v2.0.0, ..., 2.x-dev, v3.0.0-BETA1, ..., 3.x-dev, 4.x-dev] but it does not match the constraint.
  Problem 2
    - survos/api-grid-bundle is locked to version 1.5.224 and an update of this package was not requested.
    - survos/api-grid-bundle 1.5.224 requires twig/twig ^3.8 -> found twig/twig[v3.8.0, ..., 3.x-dev] but it conflicts with your root composer.json require (dev-escaper-fix).
  Problem 3

```

**Comment by fabpot** [comment]
@tacman Here you go: https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by nicklog** [comment]
Hey @fabpot

i checked out the branch and for me the fix does not resolve the problem.

```
You must call "setEscaperRuntime()" before calling "Twig\Extension\EscaperExtension::addSafeClass()".
```

```
LogicException:
You must call "setEscaperRuntime()" before calling "Twig\Extension\EscaperExtension::addSafeClass()".

  at vendor/twig/twig/src/Extension/EscaperExtension.php:180
  at Twig\Extension\EscaperExtension->addSafeClass('Symfony\\UX\\TwigComponent\\ComponentAttributes', array('html'))
     (vendor/symfony/ux-twig-component/src/Twig/TwigEnvironmentConfigurator.php:35)
  at Symfony\UX\TwigComponent\Twig\TwigEnvironmentConfigurator->configure(object(Environment))
     (var/cache/dev/ContainerFCKoKDv/App_KernelDevDebugContainer.php:2123)
  at ContainerFCKoKDv\App_KernelDevDebugContainer::getTwigService(object(App_KernelDevDebugContainer))
     (var/cache/dev/ContainerFCKoKDv/App_KernelDevDebugContainer.php:578)
  at ContainerFCKoKDv\App_KernelDevDebugContainer::get_Container_Private_ProfilerService(object(App_KernelDevDebugContainer))
     (var/cache/dev/ContainerFCKoKDv/App_KernelDevDebugContainer.php:1785)
  at ContainerFCKoKDv\App_KernelDevDebugContainer::getProfilerListenerService(object(App_KernelDevDebugContainer))
     (var/cache/dev/ContainerFCKoKDv/App_KernelDevDebugContainer.php:907)
  at ContainerFCKoKDv\App_KernelDevDebugContainer::ContainerFCKoKDv\{closure}()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:221)
  at Symfony\Component\EventDispatcher\EventDispatcher->sortListeners('kernel.response')
     (vendor/symfony/event-dispatcher/EventDispatcher.php:70)
  at Symfony\Component\EventDispatcher\EventDispatcher->getListeners('kernel.response')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:257)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->preProcess('kernel.response')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:121)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ResponseEvent), 'kernel.response')
     (vendor/symfony/http-kernel/HttpKernel.php:211)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(RedirectResponse), object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:199)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:185)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/html/vendor/autoload_runtime.php')
     (public/index.php:5)       
```

**Comment by fabpot** [comment]
@nicklog Can you test with the new version of the patch?

**Comment by nicklog** [comment]
@fabpot it works 👍🏼

**Pull request merged**
