### PR TITLE
Repair may occur under the windows "\ \" file separator

### PR DESCRIPTION
**Pull request by a939638621**
#1743  

Encoding has become the standard.

### CODE REVIEW

**Comment by a939638621** [comment]
Why？？？ where it does not meet the standard encoding？？？？

**Comment by ninsuo** [comment]
' != "

**Comment by ninsuo** [comment]
By the way there are few chances your hack will be merged without any good reason to do it.

**Comment by a939638621** [comment]
According to you said the removal of the cache and then uploaded to the Linux from the windowsNT, and did not solve the problem,
I still have to go to the source file,
If you don't believe, you can try it yourself!!
I was executing the following command to clear the cache!!

```bash
php app/console cache:clear
```

**Comment by a939638621** [comment]
Or you own the code to write, a quick release of the new version of repair!! Sincere thanks

**Comment by ninsuo** [comment]
Try: `php app/console cache:clear --env=prod`

**Pull request closed without merging**
