### PR TITLE
Fix leaks and tidy api

### PR DESCRIPTION
**Pull request by jpauli**

### CODE REVIEW

**Comment by stof** [comment]
I suggest doing this in the 1.x branch as it is still maintained

**Comment by fabpot** [comment]
@stof: it is indeed for the 1.x branch. The 2.x C ext will see many more major changes.

**Comment by stof** [comment]
then the target of the PR is wrong (which also means it does not run against all the PHP versions supported by 1.x)

**Comment by fabpot** [comment]
@jpauli Can you close this PR and resubmit it on the 1.x branch?

**Comment by stof** [comment]
@fabpot should 1.x be the default branch on github for now ?

**Comment by fabpot** [comment]
@stof That's already the case

**Pull request closed without merging**
