### PR TITLE
Changed initialization and default value of auto_reload setting

### PR DESCRIPTION
**Pull request by volchnik**
Fixing error during template rendering when:
* debug set to false
* cache directory defined and empty
* auto_reload not defined

Making auto_reload always enabled during debug is enabled.

### CODE REVIEW

**Comment by stof** [comment]
Why should it be always enabled when debug is enabled ? I don't understand the reasonning. People should be able to configure them separately

**Comment by volchnik** [comment]
Well, switching off undefined auto_reload when debug is false is also bad idea (especially for novice users)
May be the best idea is just change auto_reload default to true.

**Comment by volchnik** [comment]
Besides changing auto_reload default, reasoning for always enable auto_reload in debug mode:
enabled debug mode must be pessimistic for cache pruning.

**Comment by stof** [comment]
@volchnik the issue with your idea is that it means that setting auto_reload to false does not respect the config set by the user explicitly

**Comment by volchnik** [comment]
There will be some coupling between auto_reload and debug settings, ignoring user config in one case (debug=true&auto_reload=false). Thought this case will be useful for novice, and not really break legacy configurations.

**Comment by stof** [comment]
@volchnik but why should this coupling happen ?

**Comment by volchnik** [comment]
That case seems to be useless even harmful for those who mess with configuration

**Pull request closed without merging**
