### PR TITLE
Implement template annotation for `getExtension`

### PR DESCRIPTION
**Pull request by mitelg**
Hello there :slightly_smiling_face:  :wave: 

my first PR here :wink: 

This change would help to improve static analysis with tools like PHPStan and Psalm.

### CODE REVIEW

**Comment by stof** [comment]
if this gets accepted by @fabpot, it should also be done for `getRuntime`

**Comment by mitelg** [comment]
@stof I have done your suggestion

**Review by wouterj — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]
Awesome. Thank you.

**Comment by fabpot** [comment]
Thank you @mitelg.

**Pull request merged**
