### PR TITLE
Added bitwise shift operators

### PR DESCRIPTION
**Pull request by zorn-v**

### CODE REVIEW

**Comment by stof** [comment]
I don't think these really belong to Twig core.

**Comment by fabpot** [comment]
I agree with @stof, that does not belong to core.

**Comment by zorn-v** [comment]
How about https://github.com/fabpot/Twig/commit/c2c01dedf864fbd0a3811ba76ad933b6cb0290c4#diff-0 ?
Bitwise operators without shifting is nonsense for me.

Anyway, can you merge it in extensions at least ?
https://github.com/twigphp/Twig-extensions/pull/141

**Comment by stof** [comment]
@zorn-v the ``b-or`` filter is useful to build the binary flag for the ``json_encode`` options for instance

**Pull request closed without merging**
