### PR TITLE
Drop support for PHP < 5.5

### PR DESCRIPTION
**Pull request by SpacePossum**
I think this condition can be removed.

### CODE REVIEW

**Comment by SpacePossum** [comment]
btw. this hack can be removed as well:
https://github.com/twigphp/Twig/blob/master/lib/Twig/Extension/Core.php#L471

I just don't know how.. ;)

**Comment by Tobion** [comment]
Why close? Seems correct.

**Comment by SpacePossum** [comment]
I dropped it because it seems the test seems related to DateTimeImmutable objects as well:
https://github.com/twigphp/Twig/blob/master/lib/Twig/Extension/Core.php#L471 
so maybe it would be more correct to update the test (and the code in Core) with those objects rather then dropping the constraint?

**Comment by Tobion** [comment]
I see

**Comment by Tobion** [comment]
Fixed in #1819

**Comment by SpacePossum** [comment]
:+1:  nice!

**Pull request closed without merging**
