### PR TITLE
Add return types missed in #4211

### PR DESCRIPTION
**Pull request by smnandre**
Complete #4211 (sorry)

I forgot to update the docs, and found some others in RuntimeLoader(s)

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @smnandre.

**Comment by smnandre** [comment]
@fabpot 

Do we need or plan to do it for `all` missing return types in the Twig 4.x codebase ? 

There is still a lot of them (with or without @return tags)

Examples:

* TemplateWrapper:unwrap (`@private`)
* ExpressionParser::parseArrow (private)
* ExpressionParser::parseStringExpression (public)
* Template::renderParentBlock() (`@internal`) 
* Environment::getCache() (public)

**Comment by fabpot** [comment]
I suppose we can start with everything private (arg and return types), maybe everything `@internal` as well?

**Comment by smnandre** [comment]
@fabpot started this here https://github.com/twigphp/Twig/pull/4218

Most of concerned methods are in fact public or protected :|

**Pull request merged**
