### PR TITLE
Fixes twigphp/Twig#1423

### LINKED ISSUE #1423: Whitespace control - trim spaces, but not newlines?
Example code:

``` html+django
  <pre>
       {{- "My lovely poem:" }}

       {{- "I love twig, oh my, let's make it better, don't ask why!" }}
      {# ^ note this minus sign #}
  </pre>
```

The output html would render as:

`My lovely poem:I love twig, oh my, let's make it better, don't ask why!`

Why? Becouse it not only removes all the spaces, but also newline characters.

Is there a way to "remove all spaces/tabs" until a twig block/character OR newline?

The desired output is:

```
My lovely poem:

I love twig, oh my, let's make it better, don't ask why!
```

I imagine it could be achieved by introduceing another whitespace control sign (that could replace the minus marked in comment) which would work similar to the `-`, but it would stop at newline character.

Or is it already possible somehow? If so - how?

### PR DESCRIPTION
**Pull request by petski**
This pull request fixes twigphp/Twig#1423

Patches more or less copied from twigphp/Twig#1569

### CODE REVIEW

**Comment by petski** [comment]
If maintainers are happy with this PR, I'd be happy to create a PR for the 1.x branch too.

**Comment by fabpot** [comment]
@petski new features should be added to the 1.x branch. We then merge the 1.x branch to the 2.x one.

**Comment by stof** [comment]
This misses the update of the doc...

**Comment by fabpot** [comment]
@petski After playing with this a bit, I can several possible improvements. I'm going to take over, apply the patch to 1.x and add/modify things. Thank you.

**Comment by petski** [comment]
Thanks in advance! 

In case it may help, I have a patch ready for the 1.x branch as petski/Twig@4c62bc853f426760af64a087cebe3d93e42b2468

(Of course, this patch doesn't include the improvements you have in mind).

**Comment by fabpot** [comment]
closing in favor of #2925

**Pull request closed without merging**
