### PR TITLE
[Extra][Markdown] Allow more variant of MD converter

### PR DESCRIPTION
**Pull request by lyrixx**
I want to inject `GithubFlavoredMarkdownConverter` but ATM, it's not possible

ref: https://github.com/thephpleague/commonmark#-installation--basic-usage

### CODE REVIEW

**Comment by stof** [comment]
it would be even better to use the interfaces for that

**Comment by lyrixx** [comment]
But we need to deal with legacy code I guess :/

**Comment by stof** [comment]
Well, then allow both the new interface and the legacy one.

**Comment by lyrixx** [comment]
I miss some time to finish it. Sorry

**Pull request closed without merging**
