### PR TITLE
Update include.rst

### PR DESCRIPTION
**Pull request by Chrysweel**
Fix in function include to set a filter

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
:+1: Good catch. But this goes on 1.x

**Comment by Chrysweel** [comment]
And I think that if it is recommended to use the function include instead of the tag, I could change all the examples to use the function. But I have not done it because maybe you do not want to change.

**Comment by Chrysweel** [comment]
Yes @lyrixx but this documentation is about 2.x the documentation about 1.x is in https://twig.symfony.com/doc/1.x/tags/include.html and has not this error in include.rst

**Comment by fabpot** [comment]
Good catch, thanks @Chrysweel.

**Pull request merged**
