### PR TITLE
fix syntax error when compiling capture nodes

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by smnandre** [comment]
Wow thanks for the reactivity ! 

I tried your updates, it solves the first errors :) 

But (sorry) there still is a similar problem with the `profile_search_filter` macro, generating this PHP code: 


```php

        $blocks = [];

        return         $__internal_5a27a8ba21ca79b61932376b2fa922d2 = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->enter($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "macro", "profile_search_filter"));

(function () use (&$context, $macros) {
            ob_start(function () { return ''; });
            try {
                // line 4
                if (CoreExtension::getAttribute($this->env, $this->source, ($context["request"] ?? null), "hasSession", [], "any", false, false, false, 4)) {
                    // line 5
                    echo "<a href=\"";
                    echo Twig\Extension\EscaperExtension::escape($this->env, $this->extensions['Symfony\Bridge\Twig\Extension\RoutingExtension']->getPath("_profiler_search_results", Twig\Extension\CoreExtension::arrayMerge(Twig\Extension\CoreExtension::arrayMerge(CoreExtension::getAttribute($this->env, $this->source, CoreExtension::getAttribute($this->env, $this->source, ($context["request"] ?? null), "query", [], "any", false, false, false, 5), "all", [], "any", false, false, false, 5), ["token" => CoreExtension::getAttribute($this->env, $this->source, ($context["result"] ?? null), "token", [], "any", false, false, false, 5)]), [($context["property"] ?? null) => (($__internal_compile_0 = ($context["result"] ?? null)) && is_array($__internal_compile_0) || $__internal_compile_0 instanceof ArrayAccess ? ($__internal_compile_0[($context["property"] ?? null)] ?? null) : null)])), "html", null, true);
                    echo "\" title=\"Search\"><span title=\"Search\" class=\"sf-icon sf-search\">";
                    echo Twig\Extension\CoreExtension::source($this->env, "@WebProfiler/Icon/search.svg");
                    echo "</span></a>";
                }

                return ('' === $tmp = ob_get_contents()) ? '' : new Markup($tmp, $this->env->getCharset());
            } finally {
                ob_end_clean();
            }
        })();        
        $__internal_5a27a8ba21ca79b61932376b2fa922d2->leave($__internal_5a27a8ba21ca79b61932376b2fa922d2_prof);


    }
```

**Comment by xabbuh** [comment]
You are right. I am on it. That's related to how the output capturing works now. I'll keep you posted. :)

**Comment by xabbuh** [comment]
here is an alternative implementation that changes the way how we deal with the `CaptureNode` which feels more clean to me: #3957

**Comment by fabpot** [comment]
Closing in favor of #3957

**Pull request closed without merging**
