### PR TITLE
[Doc] Modernize Class name in examples

### PR DESCRIPTION
**Pull request by smnandre**
From "Project_Twig_Extension" to "CustomExtension"

Just a suggestion, feel free to close if you want to keep it like this :)

I found those namings only in "advanced"

### CODE REVIEW

**Comment by fabpot** [comment]
That makes a lot of sense to me. Have you change them all?

**Comment by smnandre** [comment]
> That makes a lot of sense to me. Have you change them all?

I looked for other `Foo_Bar_Class` and could not find one.. it seems the remaining were mostly in this advanced page.



But i noticed something "similar-ish" a couple weeks ago (and forgot to note it...) i'll look if i can find it again

**Comment by smnandre** [comment]
Got it :) https://github.com/twigphp/Twig/pull/4117

**Comment by fabpot** [comment]
Thank you @smnandre.

**Pull request merged**
