### PR TITLE
Use PHP 7.1 features : `is_iterable`, `??` and `?:`

### PR DESCRIPTION
**Pull request by GromNaN**
Apply the following changes with rector, compatible with PHP 7.1:

```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/doc',
        __DIR__ . '/tests',
        __DIR__ . '/extra',
    ]);
    $rectorConfig->rule(\Rector\Php53\Rector\Ternary\TernaryToElvisRector::class);
    $rectorConfig->rule(\Rector\Php70\Rector\Ternary\TernaryToNullCoalescingRector::class);
    $rectorConfig->rule(\Rector\Php71\Rector\BooleanOr\IsIterableRector::class);
};
```

### CODE REVIEW

**Comment by GromNaN** [comment]
You may want to switch to `::class` constant for all referenced class names.
```php
    $rectorConfig->rule(\Rector\Php55\Rector\String_\StringClassNameToClassConstantRector::class);
```

**Comment by fabpot** [comment]
We don't update 2.x anymore except for bug fixes. Can you retarget on 3.x?

**Comment by GromNaN** [comment]
Also replaced calls to `twig_test_iterable` with `is_iterable`. The function `twig_test_iterable` is deprecated to be removed in 4.0.

**Comment by fabpot** [comment]
Thank you @GromNaN.

**Pull request merged**
