### PR TITLE
changed default arg values of Twig_Source constructor to empty strings

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by stof** [comment]
the name is still optional, which breaks compilation of templates, as Twig now always expects the name to be populated. It reads it from the Twig_Source instead of storing it in the stream itself: https://github.com/twigphp/Twig/blob/9c502248378e9422759fab05464db774966c22c7/lib/Twig/Node/Module.php#L52 for instance (but many other places too)

btw, Twig_Environment should probably even have a safeguard ensuring that the Twig_Source given by the loader has the same name than the one it asked for.

**Comment by fabpot** [comment]
I don't understand your concern. An empty name is a valid name. I don't see why we would require a non-empty name.

**Comment by fabpot** [comment]
Having a template name helps a lot (debugging, ...), but it's not a hard requirement.

**Comment by fabpot** [comment]
nervermind

**Pull request closed without merging**
