### PR TITLE
Fixed ArrayObject access with a null value

### PR DESCRIPTION
**Pull request by yceruto**
fixes https://github.com/twigphp/Twig/issues/2744

### CODE REVIEW

**Comment by stof** [comment]
`array_key_exists` on an object does not use their ArrayAccess interface, but is an alias of `property_exists`. So that code does not do the right thing

**Comment by stof** [comment]
btw, when testing things for ArrayAccess, don't do it *only* with ArrayObject, as that one is a special case (ArrayObject has some magic allowing to mix array access and property access, which might be why things are working in your particular case)

**Comment by yceruto** [comment]
> array_key_exists on an object does not use their ArrayAccess interface, but is an alias of property_exists. So that code does not do the right thing

It depends how your `ArrayObject` is defined, right? This solution should cover three cases https://3v4l.org/kOVRn, https://3v4l.org/16e5v and https://3v4l.org/S4rs6:
```php
$object = new ArrayObject(['foo' => null]);
// or
$object = new ArrayObject();
$object['foo'] = null;
// or
$object = new ArrayObject(['foo' => null], ArrayObject::ARRAY_AS_PROPS);
```

> btw, when testing things for ArrayAccess, don't do it only with ArrayObject, as that one is a special case (ArrayObject has some magic allowing to mix array access and property access, which might be why things are working in your particular case)

There is already a test for ArrayAccess here:
https://github.com/twigphp/Twig/blob/5d166a4297ab89da37aebc592aa049dff98862d5/test/Twig/Tests/TemplateTest.php#L317

**Comment by yceruto** [comment]
However, I found that by using [the `ArrayObject` flags](http://php.net/manual/en/class.arrayobject.php#arrayobject.constants.flags) or assigning values as properties doesn't work either https://3v4l.org/vAsiv. Same issue here:
https://github.com/twigphp/Twig/blob/5d166a4297ab89da37aebc592aa049dff98862d5/lib/Twig/Template.php#L580

**Comment by yceruto** [comment]
However, I found that by initializing `$object->foo = null` doesn't work either https://3v4l.org/vAsiv. So same issue here:
https://github.com/twigphp/Twig/blob/5d166a4297ab89da37aebc592aa049dff98862d5/lib/Twig/Template.php#L580

**Comment by nikic** [comment]
Just as a heads up, it is likely that the ability to use `array_key_exists` on objects in general and `ArrayObject` in particular will go away in the future, so please do not rely on this.

If you would like to special-case `ArrayObject` in particular you can call the `offsetExists()` method (which will treat null values as existing). However, this is not true of `ArrayAccess` objects in general.

**Review by Tobion — APPROVED** [review]
Seems to be the correct way to fix #2744
That this solution might not be future-proof according to @nikic is a different problem as that would also require more changes from what I can see, like in https://github.com/twigphp/Twig/blob/5d166a4297ab89da37aebc592aa049dff98862d5/lib/Twig/Template.php#L580
This can be dealt with when the time comes.

**Comment by yceruto** [comment]
Resolved conflicts.

**Comment by fabpot** [comment]
Thank you @yceruto.

**Comment by fabpot** [comment]
@yceruto That breaks some tests on the 2.x branch. Can you have a look please?

**Comment by yceruto** [comment]
It should be fixed in https://github.com/twigphp/Twig/pull/2809

**Comment by stof** [comment]
does `array_key_exists` work for any ArrayAccess implementation ? Or only for ArrayObject ?

**Comment by nikic** [comment]
@stof `array_key_exists` does not work with ArrayAccess objects. `ArrayObject` uses a special overload to be usable with `array_key_exists` (and this is orthogonal to its ArrayAccess implementation -- e.g. a child class overriding offsetExists will not be able to influence the behavior). This functionality is retained for backwards compatibility reasons (I believe ZF1 used this is a pretty central location) and I expect that we'll drop it in PHP 8.

**Comment by stof** [comment]
then this PR is wrong.

**Comment by nikic** [comment]
To be more precise `array_key_exists` "works" on all objects, but it's going to check the existence of properties. So if there's an ArrayAccess object that has a public `->foo` but no `['foo']` then I think this code will misbehave, because `array_key_exists` will return true, but `['foo']` will access a non-existent offset. Might be worthwhile to add a test for such a case.

**Pull request merged**
