### PR TITLE
Make FilesystemLoader::findTemplate public

### PR DESCRIPTION
**Pull request by ruudk**
For [TwigStan](https://github.com/twigstan/twigstan), I want to be able to find a template by the namespaced path. 

Currently, the only way to do this is to use getSourceContext() but this also loads the template into memory.

/cc @fabpot

### CODE REVIEW

**Comment by stof** [comment]
I'm -1 on that change. This would encourage writing code that works only for the FilesystemLoader instead of supporting any configured loader (note that in a Symfony 7.2 project, the twig loader registered in the environment is *not* a FilesystemLoader but a ChainLoader).

**Comment by ruudk** [comment]
Any suggestions on how to resolve it to a file on disk then? This only applies to FilesystemLoader as Loader can load from anywhere.

**Comment by stof** [comment]
why do you need to resolve to a file path ? this will conflict with support for other loaders

**Comment by ruudk** [comment]
I came up with a different approach that does not require me to resolve this afterwards.

**Pull request closed without merging**
