### PR TITLE
Remove boilerplate to run tests on PHP 8

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Follows https://github.com/symfony/symfony/pull/36882

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Fails for now. Caching on Travis makes this green, but [here is another build](https://travis-ci.org/github/nicolas-grekas/Twig/jobs/689352091) I need to debug.

**Comment by stof** [comment]
this looks like an issue in the bridge itself

**Comment by stof** [comment]
I'm quite sure it is https://github.com/symfony/symfony/pull/36882/files#r428221377

**Comment by nicolas-grekas** [comment]
I removed that line while merging up. I'll have a look later...

**Comment by nicolas-grekas** [comment]
Now [green](https://travis-ci.org/github/nicolas-grekas/Twig/jobs/689352091).
Fixed in [this commit](https://github.com/symfony/symfony/commit/606715b6eca987cfe8d0e3a8be6571e637f0c4ef).

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
