### PR TITLE
Remove obsolete "requires PHP" annotation

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
As the work has already been done in 4.x, I don't want us to do it again in 3.x now that we've bumped the min PHP version to 8.0.

**Comment by derrabus** [comment]
This PR removes two annotations. One of them is still present on 4.x, while the other one is gone. So my change actually contains one line removal "done again" on 3.x. Well… 😓 

Shall I rebase the PR onto 4.x?

**Comment by derrabus** [comment]
Rebased. 🙂

**Comment by fabpot** [comment]
Thank you @derrabus.

**Pull request merged**
