### PR TITLE
Update random.rst

### PR DESCRIPTION
**Pull request by nzubkov**
added a new way to get a random number from the range.

### CODE REVIEW

**Comment by stof** [comment]
Well, that's the same than the first example, as you are also passing an array as argument. I don't think we need to provide examples for all possible ways to get an array to pass it in the argument.

**Comment by SpacePossum** [comment]
it is a not so efficient way for a min. max. as it creates an array with an element for each value in the range, couldn't Twig support `random(min, max)` ?

**Comment by fabpot** [comment]
I agree with @stof. Let's close it.

**Comment by apfelbox** [comment]
@SpacePossum you can always fake it with `min + random(max - min)`. Would still be convenient to add it directly, though.

**Pull request closed without merging**
