### PR TITLE
Fix PHP_FE_END value

### PR DESCRIPTION
**Pull request by remicollet**
See explanation on rev c41d305

### CODE REVIEW

**Comment by fabpot** [comment]
ping @jpauli

**Comment by jpauli** [comment]
? Can't merge, there is no merge button ...

**Comment by stof** [comment]
@jpauli I guess he is asking for your :+1: before merging, not for merging yourselves

**Comment by jpauli** [comment]
It is OK to merge

**Comment by fabpot** [comment]
Thank you @remicollet.

**Pull request merged**
