### PR TITLE
Minor rename of Sandbox test: functions->methods

### PR DESCRIPTION
**Pull request by YSaxon**

### CODE REVIEW

**Comment by stof** [comment]
Should be done in 3.x as the 2.x branch receives only bug fixes now (until its end of maintenance at the end of December 2023)

**Comment by YSaxon** [comment]
@stof

**Comment by stof** [comment]
I don't have merge rights. I only have triage permissions on the repo. You will need @fabpot for the merge.

**Comment by fabpot** [comment]
Thank you @YSaxon.

**Pull request merged**
