### PR TITLE
Starting to implement https://github.com/twigphp/Twig/issues/2930

### PR DESCRIPTION
**Pull request by ThomasLandauer**
See https://github.com/twigphp/Twig/issues/2930

### CODE REVIEW

**Comment by fabpot** [comment]
@ThomasLandauer Is it still WIP?

**Comment by ThomasLandauer** [comment]
To be honest: I don't know ;-) Please take a look and tell me what to do next.

**Comment by fabpot** [comment]
@ThomasLandauer I've finished the work here.

**Comment by fabpot** [comment]
Thank you @ThomasLandauer.

**Pull request merged**
