### PR TITLE
Fix using array_key_exists() on objects, it is deprecated in PHP 7.4

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Found as part of https://github.com/symfony/symfony/issues/32844

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by alcaeus** [comment]
@fabpot @nicolas-grekas when will this be released? This is holding up PHP 7.4 compatibility for DoctrineBundle.

**Comment by fabpot** [comment]
@alcaeus I've just released a new version of 1.x.

**Comment by alcaeus** [comment]
Thank you! ❤️

**Pull request merged**
