### PR TITLE
Implemented filesystem cache, one and only (see #1415)

### PR DESCRIPTION
**Pull request by andrewtch**

### CODE REVIEW

**Comment by guilhermeaiolfi** [comment]
So, what's the status on this?

**Comment by andrewtch** [comment]
I'm still wating for @fabpot to answer.

**Comment by F21** [comment]
It this still being targeted for 2.0?

**Comment by andrewtch** [comment]
I can try to update it if anyone is still interested.

**Comment by F21** [comment]
@andrewtch Would love to see it happen. I am planning to build a twig rendering microservice that will render templates uploaded by users. The service will be deployed to a docker container and will be immutable. It makes sense to be able to place the template cache somewhere else so that we don't have to warm the cache during every deploy.

**Comment by stof** [comment]
@F21 Put the cache in a folder which is not cleared between deployments (but take care to clear it when you deploy a Twig update as the cached templates are not meant to be compatible with any Twig version but only with the version generating them, so some Twig updates may not allow reusing the same cached template)

**Comment by fabpot** [comment]
closing in favor of #1812 which is built on top of this PR.

**Pull request closed without merging**
