### PR TITLE
Re-add compat with PHP 7.1

### LINKED ISSUE #3613: release a PHP 7.1 and PHP 8.1 Twig version
As said in by @fabpot (https://github.com/phpmyadmin/phpmyadmin/issues/16746#issuecomment-993014793) "we can probably re-add PHP 7.1 support for a "special" release."

Problem explained: https://github.com/phpmyadmin/phpmyadmin/issues/16746#issuecomment-991394796
PHP version drop: https://github.com/twigphp/Twig/pull/3410

Here is the commit list that should be picked on a branch to be released before the PHP 7.2 version restriction. Other solution, remove the PHP version restriction, release and put it back.

Commit/PR/issues list (used https://github.com/twigphp/Twig/search?q=8.1&state=closed&type=issues):
- https://github.com/twigphp/Twig/pull/3536
- https://github.com/twigphp/Twig/pull/3535
- https://github.com/twigphp/Twig/issues/3534
- https://github.com/twigphp/Twig/issues/3494
- https://github.com/twigphp/Twig/pull/3554
- https://github.com/twigphp/Twig/pull/3505
- https://github.com/twigphp/Twig/pull/3552
- **parts of this commit: https://github.com/twigphp/Twig/commit/47201dc3bccf6ebfa507612f8e5402ad0570820f**

Let me know what I can do.

This is the last step for us to provide a PHP 7.1 and 8.1 compatible version in a clean way. Else I will have to apply patches manually after composer install. Everyone would agree that it would be way less clean than a special release.

### PR DESCRIPTION
**Pull request by fabpot**
Closes #3613

### CODE REVIEW

**Comment by fabpot** [comment]
@williamdes Can you confirm that this is enough for you?
If yes, I will make a new release (and I won't revert back, let's keep it with 7.1 support until it becomes a problem).

**Comment by williamdes** [comment]
> @williamdes Can you confirm that this is enough for you? If yes, I will make a new release (and I won't revert back, let's keep it with 7.1 support until it becomes a problem).

Thank you !
This is perfect for us and a lot of users

**Comment by fabpot** [comment]
New release is out now!

**Comment by williamdes** [comment]
> New release is out now!

Awesome !
💯 🚀

**Pull request merged**
