### PR TITLE
Added RuntimeExtensionInterface

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
rebase needed

**Comment by lyrixx** [comment]
rebased

**Comment by fabpot** [comment]
This PR should be done on the 1.x branch.

**Comment by nicolas-grekas** [comment]
On 1.x, this means it needs to be an "underscore" class, with namespaced FC layer, isn't it?

**Comment by lyrixx** [comment]
I'll wait for @fabpot's feedback before updating the PR

**Comment by fabpot** [comment]
I have no problem in adding new feature that would be using namespaced class names instead of _ ones. The changelog should just mention that this is restricted to PHP 5.3 only.

**Comment by fabpot** [comment]
@lyrixx?

**Comment by lyrixx** [comment]
PR updated. Sorry for the delay.

**Pull request merged**
