### PR TITLE
removed remaining mentions of the C extension

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by stof** [comment]
shouldn't this wait to see the result of #2310 ?

**Comment by fabpot** [comment]
Yes and no. I think it's going to take time to get feedback from users. As my first tests shows that the gains are quite minimal, I think I'm going to release 2.0 without a C extension and add it in 2.x if people prove that it helps significantly on their applications.

**Comment by stof** [comment]
then most of these needs to be reverted in #2310, right ? Then, OK for this PR

**Comment by fabpot** [comment]
Of course, that's what I will do when merged.

**Pull request merged**
